### ISSUE TITLE
sys.exit(1) called during `handle_retry_test_instruction`

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/storage-testbench#67]
While attempting to run the java retry conformance tests I found that eventually my test suite would hang with SocketTimeout errors due to workers closing due to `sys.exit(1)`.

Traceback:
```
CRITICAL:concurrent.futures:Exception in worker
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 54, in run 
    self.future.set_exception(exc)
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 554, in set_exception
    self._invoke_callbacks()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 238, in finish_request
    (keepalive, conn) = fs.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run 
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/storage-testbench/testbench/handle_gzip.py", line 33, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/storage-testbench/emulator.py", line 101, in wrapper
    response_handler = testbench.common.handle_retry_test_instruction(
  File "/opt/storage-testbench/testbench/common.py", line 409, in handle_retry_test_instruction
    sys.exit(1)
SystemExit: 1
```

Full stdout and stderr logs attached.
[stderr.log](https://github.com/googleapis/storage-testbench/files/7024507/stderr.log)
[stdout.log](https://github.com/googleapis/storage-testbench/files/7024508/stdout.log)

**Comment by BenWhitehead** [comment]
This appears to only happen when `return-reset-connection` is used in the instructions. I don't see this happen if I constrain the tests to use other return instructions.

I'm running the server with this command:
```bash
gunicorn --bind "localhost:9000" --worker-class sync --threads 10 --access-logfile - "emulator:run()"
```

**Comment by coryan** [comment]
That is intentional, but maybe unnecessary.  The intent of `return-reset-connection` is to close the socket, since more or less forever we have terminated one of the `gunicorn` tasks to do this.  This is the code in `google-cloud-cpp`:

https://github.com/googleapis/google-cloud-cpp/blob/8794ddcc40c2211ada81c4d67a782112ba864504/google/cloud/storage/emulator/utils/common.py#L402-L407

It is also true with the older instructions:

https://github.com/googleapis/google-cloud-cpp/blob/8794ddcc40c2211ada81c4d67a782112ba864504/google/cloud/storage/emulator/gcs/object.py#L433-L444

With that said, if this is causing problems (is it? do the tests for your client library pass despite this?), maybe we should not exit (raising an exception seems reasonable). 

Thoughts?

**Comment by BenWhitehead** [comment]
Interesting, I never saw this error when running the emulator from the cpp repo. With the testbench eventually my whole suite will failed with socket timeout errors (I guess because all the workers have exited). Do workers restart automatically? Or am I missing an arg to gunicorn to tell it to do that?
